### ISSUE TITLE
Different version of Julia qouted 

### ISSUE THREAD

**Issue by smartgh0** [CEVE-421-521/lab-01#1]
https://github.com/CEVE-421-521/lab-01/blob/f1107128918f0aa1e007b678400f92125782d60e/index.qmd#L103 states Julia 1.9 should be installed, but actual Julia that was established in the example shown or required was Julia 1.10.

**Comment by jdossgollin** [comment]
Good catch + linked in, +2 points (keep this receipt!)

**Comment by jdossgollin** [comment]
Should be fixed in [ccee202877cff88571fc8bcf5901e51b8fc6859a](https://github.com/CEVE-421-521/lab-01/commit/ccee202877cff88571fc8bcf5901e51b8fc6859a)
